brew "git"
brew "fish"
brew "zsh"
brew "neovim"
brew "herdr"
brew "tmux"
brew "lazygit"
brew "hunk"
brew "mise"
brew "atuin"
brew "gh"
brew "ripgrep"
brew "tree-sitter-cli"
brew "cmake"
brew "ninja"
brew "uv"
brew "xclip" if OS.linux?
brew "wl-clipboard" if OS.linux?
