# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/v0.56.0/schema/config.json
git:
  pagers:
    - pager: hunk pager
gui:
  theme:
    selectedLineBgColor:
      - "#404447"
